name: Resources and Code Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TS_NODE_COMPILER: ttypescript
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Resources check
        run: |
          npm install
          npm run check
          npm run build
        working-directory: ./package

      - name: Code check
        run: |
          npm run lint
          npm run test
