name: Resources and Code Check

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TS_NODE_COMPILER: ttypescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm ci

      - name: Resources check
        run: cd ./package && npm run check

      - name: Code check
        run: |
          npm run build:resources
          npm run lint
          npm run test
