name: Package Compile and Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RMG_BUILD_AND_RELEASE }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        working-directory: ./package

      - name: Pre-publish
        run: |
          chmod +x ./scripts/prepublish.sh
          ./scripts/prepublish.sh
        id: prepublish

      - name: Publish to npm
        run: |
          cd ./package/dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}

  rebuild:
    needs: publish
    uses: railmapgen/rmg-palette/.github/workflows/build.yml@master
    with:
      auth_deploy: PRD
    secrets: inherit
